using Robust.Client.UserInterface.CustomControls;
//SS220-LabelColors begin
using System.Linq;
using Content.Client.Decals.UI;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
//SS220-LabelColors end
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Labels.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class HandLabelerWindow : DefaultWindow
    {
        public event Action<string>? OnLabelChanged;
        public event Action<Color>? OnColorChanged; //SS220-LabelColors

        /// <summary>
        /// Is the user currently entering text into the control?
        /// </summary>
        private bool _focused;
        // TODO LineEdit Make this a bool on the LineEdit control

        private string _label = string.Empty;
        private string _initialLabel = string.Empty;

        //SS220-LabelColors begin
        private PaletteColorPicker? _colorPicker;
        private readonly StyleBoxFlat _swatch;
        //SS220-LabelColors end

        public HandLabelerWindow()
        {
            RobustXamlLoader.Load(this);

            LabelLineEdit.OnTextChanged += e =>
            {
                _label = e.Text;
                OnLabelChanged?.Invoke(_label);
                UpdateButtons();
            };

            LabelLineEdit.OnFocusEnter += _ => _focused = true;
            LabelLineEdit.OnFocusExit += _ =>
            {
                _focused = false;
                LabelLineEdit.Text = _label;
            };
            ResetLabelButton.OnPressed += _ => LabelLineEdit.SetText(_initialLabel, true);
            ClearLabelButton.OnPressed += _ => LabelLineEdit.SetText("", true);

            //SS220-LabelColors begin
            _swatch = new StyleBoxFlat { BackgroundColor = Color.White };
            ColorSwatch.PanelOverride = _swatch;
            ColorButton.OnPressed += _ => ToggleColorPicker();
            //SS220-LabelColors end
        }

        protected override void Opened()
        {
            base.Opened();

            // Give the editor keyboard focus, since that's the only
            // thing the user will want to be doing with this UI
            LabelLineEdit.GrabKeyboardFocus();
        }
        //SS220-LabelColors begin
        public override void Close()
        {
            _colorPicker?.Close();

            base.Close();
        }
        //SS220-LabelColors end

        public void SetCurrentLabel(string label)
        {
            if (label == _label)
                return;

            _label = label;
            if (!_focused)
            {
                LabelLineEdit.Text = label;
                UpdateButtons();
            }
        }

        public void SetInitialLabelState()
        {
            LabelLineEdit.Text = _label;
            LabelLineEdit.CursorPosition = _label.Length;
            LabelLineEdit.SelectionStart = 0;
            _initialLabel = _label;
            UpdateButtons();
        }

        public void UpdateButtons()
        {
            ResetLabelButton.Disabled = (LabelLineEdit.Text == _initialLabel);
            ClearLabelButton.Disabled = (LabelLineEdit.Text == "");
        }

        public void SetMaxLabelLength(int maxLength)
        {
            LabelLineEdit.IsValid = s => s.Length <= maxLength;
        }

        //SS220-LabelColors begin
        public void SetCurrentColor(Color color)
        {
            _swatch.BackgroundColor = color;
        }

        private void ToggleColorPicker()
        {
            if (_colorPicker is null)
            {
                _colorPicker = new PaletteColorPicker();
                _colorPicker.OpenCenteredLeft();
                _colorPicker.PaletteList.OnItemSelected += OnPaletteItemSelected;
                return;
            }

            if (_colorPicker.IsOpen)
                _colorPicker.Close();
            else
                _colorPicker.Open();
        }

        private void OnPaletteItemSelected(ItemList.ItemListSelectedEventArgs args)
        {
            var selected = args.ItemList.GetSelected().FirstOrDefault();
            if (selected?.Metadata is not Color color)
                return;

            SetCurrentColor(color);
            OnColorChanged?.Invoke(color);
        }
        //SS220-LabelColors end
    }
}
