- type: experienceDefinition
  id: NoSpecialRoleExperience
  skills:
    Bureaucracy:
      level: 2
    ExtravehicularActivity:
      level: 4
    CombatTraining:
      level: 4
    Construction:
      level: 4
    Medicine:
      level: 4
    Anatomy:
      level: 4
    PhysicalTraining:
      level: 4
  addSublevelPoints: 2000

# Used to give it to job that dont have any effect from it
# In Future it should be changed for them
- type: experienceDefinition
  id: NoExperience
  skills:
    Bureaucracy:
      level: 1
    ExtravehicularActivity:
      level: 4
    CombatTraining:
      level: 4
    Construction:
      level: 4
    Medicine:
      level: 4
    Anatomy:
      level: 4
    PhysicalTraining:
      level: 4
  addSublevelPoints: 0
