- type: experienceDefinition
  id: DetectiveRoleExperience
  skills:
    Bureaucracy:
      level: 2
    ExtravehicularActivity:
      level: 4
    CombatTraining:
      level: 4
    Construction:
      level: 4
    Medicine:
      level: 4
    Anatomy:
      level: 4
    PhysicalTraining:
      level: 4
  knowledges:
  - SecurityKnowledge
  addSublevelPoints: 10

- type: experienceDefinition
  id: HeadOfSecurityRoleExperience
  skills:
    Bureaucracy:
      level: 2
    ExtravehicularActivity:
      level: 4
    CombatTraining:
      level: 4
    Construction:
      level: 4
    Medicine:
      level: 4
    Anatomy:
      level: 4
    PhysicalTraining:
      level: 4
  knowledges:
  - InformedPersonalKnowledge
  - SecurityKnowledge
  addSublevelPoints: 10

- type: experienceDefinition
  id: SecuritySeniorRoleExperience
  skills:
    Bureaucracy:
      level: 2
    ExtravehicularActivity:
      level: 4
    CombatTraining:
      level: 4
    Construction:
      level: 4
    Medicine:
      level: 4
    PhysicalTraining:
      level: 4
  knowledges:
  - SecurityKnowledge
  addSublevelPoints: 10

- type: experienceDefinition
  id: SecurityCadetRoleExperience
  skills:
    Bureaucracy:
      level: 2
    ExtravehicularActivity:
      level: 4
    CombatTraining:
      level: 4
    Construction:
      level: 4
    Medicine:
      level: 4
    PhysicalTraining:
      level: 4
  knowledges:
  - SecurityKnowledge
  addSublevelPoints: 15

- type: experienceDefinition
  id: SecurityOfficerRoleExperience
  skills:
    Bureaucracy:
      level: 2
    ExtravehicularActivity:
      level: 4
    CombatTraining:
      level: 4
    Construction:
      level: 4
    Medicine:
      level: 4
    PhysicalTraining:
      level: 4
  knowledges:
  - SecurityKnowledge
  addSublevelPoints: 15

- type: experienceDefinition
  id: SecurityPilotRoleExperience
  skills:
    Bureaucracy:
      level: 2
    ExtravehicularActivity:
      level: 4
    CombatTraining:
      level: 4
    Construction:
      level: 4
    Medicine:
      level: 4
    PhysicalTraining:
      level: 4
  knowledges:
  - SecurityKnowledge
  addSublevelPoints: 15

- type: experienceDefinition
  id: WardenRoleExperience
  skills:
    Bureaucracy:
      level: 2
    ExtravehicularActivity:
      level: 4
    CombatTraining:
      level: 4
    Construction:
      level: 4
    Medicine:
      level: 4
    Anatomy:
      level: 4
    PhysicalTraining:
      level: 4
  knowledges:
  - SecurityKnowledge
  addSublevelPoints: 10

- type: experienceDefinition
  id: SecurityPetRoleExperience
  skills:
    Bureaucracy:
      level: 1
    ExtravehicularActivity:
      level: 4
    CombatTraining:
      level: 4
    Construction:
      level: 4
    Medicine:
      level: 4
    PhysicalTraining:
      level: 4
  knowledges:
  - SecurityKnowledge
  addSublevelPoints: 0
